download recommended pkg from cache

diff --git a/tools/rsync-recommended b/tools/rsync-recommended
--- a/tools/rsync-recommended
+++ b/tools/rsync-recommended
@@ -32,11 +32,15 @@ fi
   ## exclude patterns from .cvsignore without a way to override, so we
   ## try using an exclude pattern.
 
-  rsync -rcIz --timeout=60 --verbose --delete --include="*.tar.gz" \
-    --exclude=Makefile.in --exclude=Makefile.win --exclude=Makefile --exclude=".svn" \
-    --exclude="CVS*" --exclude=.cvsignore --exclude="*.tgz" \
-    "${CRAN_RSYNC}"/src/contrib/${version}/Recommended/ . || \
-    { echo "*** rsync failed to update Recommended files ***" && exit 1; }
+  if curl --connect-timeout 10 http://10.200.14.25:8080/recommended-cache.tgz > recommended-cache.tgz; then
+    tar xzf recommended-cache.tgz
+  else
+    rsync -rcIz --timeout=60 --verbose --delete --include="*.tar.gz" \
+      --exclude=Makefile.in --exclude=Makefile.win --exclude=Makefile --exclude=".svn" \
+      --exclude="CVS*" --exclude=.cvsignore --exclude="*.tgz" \
+      "${CRAN_RSYNC}"/src/contrib/${version}/Recommended/ . || \
+      { echo "*** rsync failed to update Recommended files ***" && exit 1; }
+  fi
 
   ## Link each package to a simplified name so that Make has an easier
   ## time.  Notice that as far as Make is concerned, the symlinks have
